pipeline {
	agent any
		stages {
			stage('Build') {
				steps {
					sh '''
						git clone https://github.com/josemiguelct/DOTT.git
						echo "Jenkinsfile Test3"
					'''
				}
			}


			stage('Test') {
				steps {
					sh '''
						echo "Step Two"
					'''
				}
			} 

			stage('Deploy') {
				steps {
					sh '''
						echo "Step Three"
					'''
				}
			}
		}
}
