pipeline {
	agent any
	tools {
        go 'GoTool'
    	}
	environment {
        GO110MODULE = 'on'
        CGO_ENABLED = 0 
        GOPATH = "${JENKINS_HOME}/Workspace/${WORKSPACE}/DOTT/cidr_convert_api/go"
    	}
		stages {
			stage('Build') {
				steps {
					sh '''
						echo "Cloning Repository and checking Go version"
						rm -rf DOTT/
						git clone https://github.com/josemiguelct/DOTT.git
						go version
						mvn -version
					'''
				}
			}

			stage('Test') {
				steps {
					echo "Testing SonarCloud"
					withSonarQubeEnv('SonarCloud') {
					sh '''
						sonar-scanner \
						-Dsonar.organization=josemiguelct \
						-Dsonar.projectKey=josemiguelct_DOTT \
						-Dsonar.sources=. \
						-Dsonar.host.url=https://sonarcloud.io
						###goop go run convert_test.go
					'''
					}	
				}
			} 

			stage('Deploy') {
				steps {
					sh '''
						echo "Deploying Go App"
						#cd DOTT/cidr_convert_api/go
						#go get github.com/Pepegasca/goop
						#goop install
						#goop go run api.go convert.go
					'''
				}
			}
		}
}
